// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // Retrieves the current platform's Firebase options
  static FirebaseOptions get currentPlatform {
    // Throw an error if the platform is web
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // Switch statement to handle different target platforms
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase options for Android
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEAJpoWVgF09TPJxq8N0HANFxARkR4Qs8',
    appId: '1:404071758441:android:4ba715b0d3e345ca6c80f8',
    messagingSenderId: '404071758441',
    projectId: 'xbridge-live',
    storageBucket: 'xbridge-live.appspot.com',
  );

  // Firebase options for iOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzYh84KHQQKCuGjmif-mA2W2ZpxD_aAi0',
    appId: '1:404071758441:ios:42d6dd29a65bbcd56c80f8',
    messagingSenderId: '404071758441',
    projectId: 'xbridge-live',
    storageBucket: 'xbridge-live.appspot.com',
    iosBundleId: 'com.tig.xbridgelive',
  );
}
